# Generated by Django 5.1.2 on 2024-11-30 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfil/')),
                ('data_conclusao', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('outro', 'Outro'), ('nao_dizer', 'Prefiro não dizer')], default='nao_dizer', max_length=10)),
                ('campus', models.CharField(max_length=100)),
                ('curso', models.CharField(max_length=100)),
                ('nivel', models.CharField(choices=[('usuario', 'Visitante'), ('editor', 'Egressos'), ('administrador', 'Administrador')], default='usuario', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
